POST http://192.168.1.63:5000/register
Content-Type: application/json

{
  "username": "cup",
  "email": "ucup@gmail.com",
  "password": "12345",
  "phone": "08123456789",
  "address": "Jl. Merpati No. 9"
}

###
POST http://192.168.1.74:5000/login
Content-Type: application/json

{
  "email": "pengguna@gmail.com",
  "password": "1"
}

###
POST http://192.168.1.63:5000/orders
Content-Type: application/json

###
GET http://192.168.1.63:5000/users

Content-Type: application/json

###
GET http://localhost:5000/auth/
Content-Type: application/json

###
DELETE http://192.168.1.22:5000/logout/

###
DELETE http://localhost:5000/delete/79b88cae-c7a0-4cd7-a13d-e066c7ccea9b

###
POST http://localhost:5000/user/
Content-Type: application/json

{
  "role_id": "8e06a3bb-23a5-4e89-9f36-123456789abc",
  "name": "Cupnurzi",
  "email": "cup@example.com",
  "password": "12345",
  "phone": "08123456789",
  "address": "Jl. Sudirman",
  "status": "active"
}

###
GET  http://localhost:5000/user/
Content-Type: application/json

###
GET http://10.143.244.155:5000/orders
Content-Type: application/json

###
GET http://192.168.1.74:5000/provider/orders
Authorization: Bearer <token>

###
GET http://192.168.1.74:5000/payments
Content-Type: application/json

