POST http://oserv.vercel.app/register
Content-Type: application/json

{
  "username": "aku",
  "email": "aku@gmail.com",
  "password": "1",
  "role": "user"
}

###
POST http://oserv.vercel.app/login
Content-Type: application/json

{
  "email": "bleh@gmail.com",
  "password": "1"
}

###
POST https://oserv.vercel.app/pesanan
Content-Type: application/json
Authorization: Bearer <token>

{
  "orders": [
    {
      "id": "uuid-123",
      "name": "John Doe",
      "phone_number": "08123456789",
      "vehicle_type": "Motor",
      "vehicle_brand": "Honda",
      "vehicle_model": "CBR 150",
      "license_plate": "B 1234 ABC",
      "color": "Merah",
      "problem_description": "Mesin tidak hidup",
      "service_type": "Servis Ringan",
      "address": "Jl. Contoh No.1",
      "status": "pending"
    }
  ]
}



###
GET http://oserv.vercel.app/users

Content-Type: application/json

###
GET http://localhost:5000/auth/
Content-Type: application/json

###
DELETE http://oserv.vercel.app/logout/

###
DELETE http://localhost:5000/delete/79b88cae-c7a0-4cd7-a13d-e066c7ccea9b

###
POST http://localhost:5000/user/
Content-Type: application/json

{
  "role_id": "8e06a3bb-23a5-4e89-9f36-123456789abc",
  "name": "Cupnurzi",
  "email": "cup@example.com",
  "password": "12345",
  "phone": "08123456789",
  "address": "Jl. Sudirman",
  "status": "active"
}

###
GET  http://localhost:5000/user/
Content-Type: application/json

###
GET http://10.143.244.155:5000/orders
Content-Type: application/json

###
GET http://192.168.1.74:5000/provider/orders
Authorization: Bearer <token>

###
GET http://192.168.1.74:5000/payments
Content-Type: application/json

